#ifndef __INCLUDE_GAMECONFIG__
#define __INCLUDE_GAMECONFIG__

#define BOARD_SIZE 8
#define PLAYER_NUM 2
#define PIECE_DIM 16
#define SCALE_F 6.0
#define SCALE_DOWN 1.0
#define PIECE_SIZE PIECE_DIM * SCALE_F
#define PIECE_PAD 10
#define EXTRA_UI 300
#define WINDOW_SIZE_X BOARD_SIZE*(PIECE_SIZE + 2*PIECE_PAD) + EXTRA_UI
#define WINDOW_SIZE_Y BOARD_SIZE*(PIECE_SIZE + 2*PIECE_PAD) 
#define WINDOW_BIND_X BOARD_SIZE*(PIECE_SIZE + 2*PIECE_PAD)
#define WINDOW_BIND_Y BOARD_SIZE*(PIECE_SIZE + 2*PIECE_PAD) 
#endif 